### ISSUE TITLE
LSTM, input gate forget gate

### ISSUE THREAD

**Issue by alper111** [afshinea/stanford-cs-229-machine-learning#1]
Hello,

I guess the description of the forget gate and the input gate should be swapped in the RNN section.

**Comment by slvher** [comment]
+1 for comment from @alper111 about the following pdf file:
https://github.com/afshinea/stanford-cs-229-machine-learning/blob/master/cheatsheet-deep-learning.pdf

**Comment by afshinea** [comment]
Great catch @alper111 and @slvher! Will correct this issue asap.
