### ISSUE TITLE
Chinese version

### ISSUE THREAD

**Issue by zhyongquan** [afshinea/stanford-cs-229-machine-learning#2]
i think your cheatsheets is very useful and want translate your cheatsheets to Chinese. is it ok?

**Comment by shervinea** [comment]
Thank you very much for your interest! 
As long as:

(1) the statement 

> Original content by Afshine Amidi and Shervine Amidi. Translation by `<insert name>`

(2) as well as the link to the original [GitHub repo](https://github.com/afshinea/stanford-cs-229-machine-learning/) and [website](https://stanford.edu/~shervine/teaching/cs-229.html)

are put at the beginning of each page, everything will be good on our side!

**Comment by zhyongquan** [comment]
OK. thanks.
