### ISSUE TITLE
miss "Tree-based and ensemble methods" in pdf

### ISSUE THREAD

**Issue by zhyongquan** [afshinea/stanford-cs-229-machine-learning#4]
there is "Tree-based and ensemble methods" in https://stanford.edu/~shervine/teaching/cs-229/cheatsheet-supervised-learning, but  no in pdf

**Comment by afshinea** [comment]
Nice catch @zhyongquan ! This was previously work in progress but is now completed and available https://github.com/afshinea/stanford-cs-229-machine-learning/blob/master/cheatsheet-supervised-learning.pdf
