### ISSUE TITLE
Error in Linear Algebra Matrix Vector multiplication

### ISSUE THREAD

**Issue by jacarvalho** [afshinea/stanford-cs-229-machine-learning#7]
First, thanks for these resources!

In VIP Refresher: Linear Algebra and Calculus, it says

> Matrix-vector multiplication – The product of matrix A \in R^{m×n} and vector x \in R^{n} is a vector of size **R^n**, such that:

Shouldn't it be instead:

> of size **R^m**, such that:

The same for Matrix-Matrix multiplication.

**Comment by shervinea** [comment]
Thanks @jacarvalho for your message. We're aware of this issue and are planning to correct it asap. Thanks for pointing it out anyway!

**Comment by Jonas1312** [comment]
Sorry to ask but when do you think you'll correct the error?

Thanks for the cheatsheets!
